# Generated by Django 2.2 on 2019-04-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0007_auto_20190417_1844'),
        ('people', '0004_auto_20190417_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hard_bounced_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inkmail.Message'),
        ),
    ]
