# Generated by Django 2.2 on 2019-04-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_person_personal_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='never_contact_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='never_contact_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
