# Generated by Django 2.2 on 2019-04-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20190417_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hash_email',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='hash_first_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='hash_last_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
