# Generated by Django 2.2 on 2019-04-18 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20190418_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='hash_email',
            new_name='hashed_email',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='hash_first_name',
            new_name='hashed_first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='hash_last_name',
            new_name='hashed_last_name',
        ),
    ]
