# Generated by Django 2.2 on 2019-05-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='raw_html',
            new_name='content',
        ),
        migrations.AddField(
            model_name='template',
            name='body_override',
            field=models.TextField(blank=True, null=True, verbose_name='Body (will overwrite all other fields).'),
        ),
        migrations.AddField(
            model_name='template',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='footer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='js',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='nav',
            field=models.TextField(blank=True, null=True),
        ),
    ]
