# Generated by Django 2.2 on 2019-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190506_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='hash_id',
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
