# Generated by Django 2.2 on 2019-05-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_page_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='everything_override',
            field=models.TextField(blank=True, null=True, verbose_name='Entire page (will override everything else)'),
        ),
    ]
