# Generated by Django 2.2.1 on 2019-05-06 21:58

from django.db import migrations, models
import django.utils.timezone
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_template_everything_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hashid', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254, unique=True)),
                ('binary_file', models.FileField(blank=True, null=True, upload_to='')),
                ('text_file', models.TextField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.models.DataDictMixin, models.Model),
        ),
    ]
