# Generated by Django 2.2.1 on 2019-05-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
