# Generated by Django 2.2.1 on 2019-05-13 13:43

from django.db import migrations, models
import django.utils.timezone
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190507_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hashid', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('url', models.CharField(max_length=1024)),
                ('target_url', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='link-images', verbose_name='Thumbnail')),
                ('destination_title', models.TextField(blank=True, null=True)),
                ('destination_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.models.DataDictMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='resource',
            name='binary_file',
            field=models.FileField(blank=True, null=True, upload_to='resources'),
        ),
    ]
