# Generated by Django 2.2.1 on 2019-05-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20190513_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
