# Generated by Django 2.2.1 on 2019-05-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20190513_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='thumbnail_image_source',
            field=models.ImageField(blank=True, null=True, upload_to='link-images-source', verbose_name='Thumbnail Source'),
        ),
    ]
