# Generated by Django 2.2.1 on 2019-05-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20190513_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='root_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='root_page',
            field=models.BooleanField(default=False),
        ),
    ]
