# Generated by Django 2.2.1 on 2019-05-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20190513_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
