# Generated by Django 2.2.1 on 2019-05-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_post_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
