# Generated by Django 2.2.1 on 2019-05-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20190515_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='source_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
