# Generated by Django 2.2.13 on 2021-02-18 05:48

from django.db import migrations, models
import django.utils.timezone
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('inkdots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('event_type', models.CharField(max_length=254)),
                ('base_url', models.CharField(max_length=512)),
                ('querystring', models.TextField()),
                ('full_url', models.TextField()),
                ('data', models.TextField(blank=True, null=True)),
                ('request_ip', models.CharField(max_length=50)),
                ('request_ua', models.CharField(max_length=512)),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.models.DataDictMixin, models.Model),
        ),
    ]
