# Generated by Django 2.2.13 on 2021-02-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkdots', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hashid',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
