# Generated by Django 3.0.8 on 2020-08-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20200810_0350'),
        ('products', '0002_auto_20200810_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
