# Generated by Django 3.0.8 on 2020-08-10 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20200810_0350'),
        ('products', '0003_auto_20200810_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='productpurchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductPurchase'),
        ),
    ]
