# Generated by Django 3.0.8 on 2020-08-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200810_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='person',
        ),
    ]
