# Generated by Django 2.2 on 2020-08-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_journeyday'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='number_of_days',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journeyday',
            name='encrypted_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
