# Generated by Django 2.2 on 2020-08-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200812_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='number_of_days',
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
