# Generated by Django 2.2 on 2020-08-17 00:38

from django.db import migrations, models
import django.utils.timezone
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200812_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hashid', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=512)),
                ('day_number', models.IntegerField(blank=True, null=True)),
                ('template', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.models.DataDictMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='journey',
            name='product',
        ),
    ]
