# Generated by Django 2.2 on 2020-08-17 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productday_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productday',
            name='name',
        ),
    ]
