# Generated by Django 2.2 on 2020-09-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='journey_noun',
            field=models.CharField(default='Sprint', max_length=512),
            preserve_default=False,
        ),
    ]
