# Generated by Django 2.2 on 2020-09-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_journey_noun'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_epilogue',
            field=models.BooleanField(default=False),
        ),
    ]
