# Generated by Django 2.2 on 2020-09-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_has_epilogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyday',
            name='last_user_action',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
