# Generated by Django 2.2.13 on 2020-10-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stripe_payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
