# Generated by Django 2.2.13 on 2020-10-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201006_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stripe_payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
