# Generated by Django 2.2.13 on 2020-10-06 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_purchase_stripe_payment_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_beta_price_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='productpurchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductPurchase'),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Purchase'),
        ),
    ]
