# Generated by Django 2.2.13 on 2020-10-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20201006_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='journey_plural_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='journey_singular_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
