# Generated by Django 2.2.13 on 2020-10-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20201008_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyday',
            name='first_user_action',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
