# Generated by Django 2.2.13 on 2020-10-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_journeyday_first_user_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyday',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
