# Generated by Django 2.2.13 on 2020-10-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_journeyday_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyday',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
