# Generated by Django 2.2.13 on 2020-11-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_journeyday_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
