# Generated by Django 2.2.13 on 2020-11-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_purchase_refund_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
