# Generated by Django 2.2.13 on 2020-11-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20201111_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='purchase_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_reciept_message', to='inkmail.OutgoingMessage'),
        ),
    ]
