# Generated by Django 2.2.13 on 2020-11-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20201111_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='journey_noun',
        ),
    ]
