# Generated by Django 2.2.13 on 2020-11-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_remove_product_journey_noun'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_downloadable',
            field=models.BooleanField(default=False),
        ),
    ]
