# Generated by Django 2.2.13 on 2020-11-15 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_bestimatorexperimentchoice_experiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestimatoranswer',
            name='name',
        ),
    ]
