# Generated by Django 2.2.13 on 2020-11-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20201116_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestimatoranswer',
            old_name='interested_in_buying',
            new_name='want_to_buy',
        ),
    ]
