# Generated by Django 2.2.13 on 2020-11-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20201116_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestimatoranswer',
            name='buy_clicked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
