# Generated by Django 2.2.13 on 2020-12-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_bestimatoranswer_buy_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyday',
            name='pre_day_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
