# Generated by Django 2.2.13 on 2020-12-07 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0012_message_purchase'),
        ('products', '0038_journeyday_pre_day_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productday',
            name='pre_day_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_pre_message', to='inkmail.OutgoingMessage'),
        ),
    ]
