# Generated by Django 2.2.13 on 2020-12-07 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_productday_pre_day_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productday',
            name='template',
        ),
        migrations.AlterField(
            model_name='productday',
            name='pre_day_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_pre_message', to='inkmail.Message'),
        ),
    ]
