# Generated by Django 2.2.13 on 2021-03-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20201207_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='help_edition',
            field=models.BooleanField(default=False),
        ),
    ]
