# Generated by Django 2.2.13 on 2021-03-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_purchase_help_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
