# Generated by Django 2.2.13 on 2021-04-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_product_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='notification_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
