# Generated by Django 2.2 on 2019-04-26 15:36

from django.db import migrations, models
import django.utils.timezone
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('hashid', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('encrypted_first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('encrypted_last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('encrypted_email', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('hashed_first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('hashed_last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('hashed_email', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('time_zone', models.CharField(blank=True, max_length=254, null=True)),
                ('was_imported', models.BooleanField(default=False)),
                ('was_imported_at', models.DateTimeField(blank=True, null=True)),
                ('import_source', models.CharField(blank=True, max_length=254, null=True)),
                ('marked_troll', models.BooleanField(default=False)),
                ('marked_troll_at', models.DateTimeField(blank=True, null=True)),
                ('banned', models.BooleanField(default=False)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('hard_bounced', models.BooleanField(default=False)),
                ('hard_bounced_at', models.DateTimeField(blank=True, null=True)),
                ('hard_bounced_reason', models.TextField(blank=True, null=True)),
                ('never_contact_set', models.BooleanField(default=False)),
                ('never_contact_set_at', models.DateTimeField(blank=True, null=True)),
                ('personal_contact', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(utils.models.DataDictMixin, models.Model),
        ),
    ]
