# Generated by Django 2.2 on 2019-04-17 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('encrypted_email', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='encrypted_email',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
