# Generated by Django 2.2 on 2019-04-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_hard_bounced_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='encrypted_email',
            field=models.CharField(blank=True, max_length=4096, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='encrypted_first_name',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='encrypted_last_name',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hashed_email',
            field=models.CharField(blank=True, max_length=4096, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hashed_first_name',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hashed_last_name',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
