# Generated by Django 2.2 on 2019-04-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_hard_bounced_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='import_source',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='was_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='was_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
