# Generated by Django 2.2 on 2019-04-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190417_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedemail',
            name='encrypted_email',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
