# Generated by Django 2.2 on 2019-04-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190419_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='encrypted_email',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hashed_email',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
