# Generated by Django 2.2 on 2019-04-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190426_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='hashed_email',
            field=models.CharField(blank=True, max_length=4096, null=True, unique=True, verbose_name='Email'),
        ),
    ]
