# Generated by Django 2.2 on 2019-04-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190417_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedEmail',
        ),
        migrations.AddField(
            model_name='person',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='hard_bounced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='hard_bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='marked_troll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='marked_troll_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
