# Generated by Django 2.2 on 2019-04-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190419_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='api_jwt_cached',
        ),
        migrations.RemoveField(
            model_name='person',
            name='inkid',
        ),
        migrations.RemoveField(
            model_name='person',
            name='salted_inkid',
        ),
    ]
