# Generated by Django 3.0.8 on 2020-07-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190428_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='patron',
            field=models.BooleanField(default=False),
        ),
    ]
