# Generated by Django 2.2 on 2019-04-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_hard_bounced_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='personal_contact',
            field=models.BooleanField(default=False),
        ),
    ]
