# Generated by Django 3.0.8 on 2020-08-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_person_patron'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='api_jwt_cached',
            field=models.CharField(blank=True, editable=False, max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='inkid',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=512, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='salted_inkid',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=512, null=True, unique=True),
        ),
    ]
