# Generated by Django 2.2.13 on 2020-12-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_person_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='turned_off_product_emails',
            field=models.BooleanField(default=False),
        ),
    ]
