# Generated by Django 2.2.13 on 2020-11-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubhouse', '0002_auto_20190426_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='hashed_email',
            field=models.CharField(blank=True, max_length=1024, null=True, unique=True, verbose_name='email'),
        ),
    ]
