from django.conf.urls import include, url
from django.contrib import admin
from clubhouse import views
from website import views as website_views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^messages/$', views.messages, name='messages'),
    url(r'^messages/new/$', views.create_message, name='create_message'),
    url(r'^message/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.message, name='message'),
    url(r'^posts/$', views.posts, name='posts'),
    url(r'^posts/new/$', views.create_post, name='create_post'),
    url(r'^post/(?P<hashid>[0-9A-Za-z_\-]+)/delete/$', views.delete_post, name='delete_post'),
    url(r'^post/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.post, name='post'),
    url(r'^pages/$', views.pages, name='pages'),
    url(r'^pages/new/$', views.create_page, name='create_page'),
    url(r'^page/(?P<hashid>[0-9A-Za-z_\-]+)/delete/$', views.delete_page, name='delete_page'),
    url(r'^page/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.page, name='page'),
    url(r'^products/$', views.products, name='products'),
    url(r'^products/new/$', views.create_product, name='create_product'),
    url(r'^product/(?P<hashid>[0-9A-Za-z_\-]+)/delete/$', views.delete_product, name='delete_product'),
    url(r'^product/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.product, name='product'),
    url(r'^productpurchases/$', views.productpurchases, name='productpurchases'),
    url(r'^productpurchases/new/$', views.create_productpurchase, name='create_productpurchase'),
    url(r'^productpurchase/(?P<hashid>[0-9A-Za-z_\-]+)/delete/$', views.delete_productpurchase, name='delete_productpurchase'),
    url(r'^productpurchase/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.productpurchase, name='productpurchase'),
    url(r'^productdays/$', views.productdays, name='productdays'),
    url(r'^productdays/new/$', views.create_productday, name='create_productday'),
    url(r'^productday/(?P<hashid>[0-9A-Za-z_\-]+)/delete/$', views.delete_productday, name='delete_productday'),
    url(r'^productday/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.productday, name='productday'),
    url(r'^purchases/$', views.purchases, name='purchases'),
    url(r'^purchases/new/$', views.create_purchase, name='create_purchase'),
    url(r'^purchase/(?P<hashid>[0-9A-Za-z_\-]+)/delete/$', views.delete_purchase, name='delete_purchase'),
    url(r'^purchase/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.purchase, name='purchase'),
    url(r'^journeys/$', views.journeys, name='journeys'),
    url(r'^journeys/new/$', views.create_journey, name='create_journey'),
    url(r'^journey/(?P<hashid>[0-9A-Za-z_\-]+)/delete/$', views.delete_journey, name='delete_journey'),
    url(r'^journey/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.journey, name='journey'),
    url(r'^bestimators/$', views.bestimators, name='bestimators'),
    url(r'^bestimators/new/$', views.create_bestimator, name='create_bestimator'),
    url(r'^bestimator/(?P<hashid>[0-9A-Za-z_\-]+)/delete/$', views.delete_bestimator, name='delete_bestimator'),
    url(r'^bestimator/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.bestimator, name='bestimator'),
    url(r'^bestimator-choices/$', views.bestimator_choices, name='bestimator_choices'),
    url(r'^bestimator-choices/new/$', views.create_bestimator_choice, name='create_bestimator_choice'),
    url(
        r'^bestimator-choice/(?P<hashid>[0-9A-Za-z_\-]+)/delete/$',
        views.delete_bestimator_choice, name='delete_bestimator_choice'
    ),
    url(r'^bestimator-choice/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.bestimator_choice, name='bestimator_choice'),
    url(r'^patrons/$', views.patrons, name='patrons'),
    url(r'^templates/$', views.templates, name='templates'),
    url(r'^templates/new/$', views.create_template, name='create_template'),
    url(r'^template/(?P<hashid>[0-9A-Za-z_\-]+)/delete/$', views.delete_template, name='delete_template'),
    url(r'^template/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.template, name='template'),
    url(r'^resources/$', views.resources, name='resources'),
    url(r'^resources/new/$', views.create_resource, name='create_resource'),
    url(r'^resource/(?P<hashid>[0-9A-Za-z_\-]+)/delete/$', views.delete_resource, name='delete_resource'),
    url(r'^resource/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.resource, name='resource'),
    url(r'^links/$', views.links, name='links'),
    url(r'^links/new/$', views.create_link, name='create_link'),
    url(r'^link/(?P<hashid>[0-9A-Za-z_\-]+)/delete/$', views.delete_link, name='delete_link'),
    url(r'^link/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.link, name='link'),
    url(r'^people/$', views.people, name='people'),
    url(r'^organization/$', views.organization, name='organization'),
    url(r'^person/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.person, name='person'),
    url(r'^subscriptions/$', views.subscriptions, name='subscriptions'),
    url(r'^subscription/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.subscription, name='subscription'),
    url(r'^newsletters/$', views.newsletters, name='newsletters'),
    url(r'^newsletters/new/$', views.create_newsletter, name='create_newsletter'),
    url(r'^newsletter/(?P<hashid>[0-9A-Za-z_\-]+)/$', views.newsletter, name='newsletter'),
    url(r'^scheduled_newsletter_messages/$', views.scheduled_newsletter_messages, name='scheduled_newsletter_messages'),
    url(
        r'^scheduled_newsletter_messages/new$',
        views.create_scheduled_newsletter_message,
        name='create_scheduled_newsletter_message'
    ),
    url(
        r'^scheduled_newsletter_message/(?P<hashid>[0-9A-Za-z_\-]+)/$',
        views.scheduled_newsletter_message,
        name='scheduled_newsletter_message'
    ),
    url(
        r'^scheduled_newsletter_message/(?P<hashid>[0-9A-Za-z_\-]+)/queue/$',
        views.scheduled_newsletter_message_confirm_queue,
        name='scheduled_newsletter_message_confirm_queue'
    ),
    url(
        r'^scheduled_newsletter_message/(?P<hashid>[0-9A-Za-z_\-]+)/queue-confirm/$',
        views.scheduled_newsletter_message_queued,
        name='scheduled_newsletter_message_queued'
    ),
    url(r'^favicon.ico$', website_views.favicon, name='favicon'),
]
