# Generated by Django 2.2 on 2019-04-19 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=254, null=True)),
                ('body_text_unrendered', models.TextField(blank=True, null=True)),
                ('body_html_unrendered', models.TextField(blank=True, null=True)),
                ('reward_image', models.ImageField(blank=True, null=True, upload_to='awesome', verbose_name='Reward Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('internal_name', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_email', models.TextField(max_length=254)),
                ('from_name', models.TextField(max_length=254)),
                ('unsubscribe_footer', models.TextField(max_length=254)),
                ('transactional_footer', models.TextField(max_length=254)),
                ('unsubscribe_if_no_hearts_after_days', models.BooleanField(default=False)),
                ('unsubscribe_if_no_hearts_after_days_num', models.IntegerField(blank=True, default=184, null=True)),
                ('unsubscribe_if_no_hearts_after_messages', models.BooleanField(default=True)),
                ('unsubscribe_if_no_hearts_after_messages_num', models.IntegerField(blank=True, default=26, null=True)),
                ('confirm_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_for_confirm', to='inkmail.Message')),
                ('welcome_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_for_welcome', to='inkmail.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('send_at', models.DateTimeField()),
                ('attempt_complete', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('subscribed_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('subscription_url', models.TextField(blank=True, null=True)),
                ('subscribed_from_ip', models.CharField(blank=True, max_length=254, null=True)),
                ('double_opted_in', models.BooleanField(default=False)),
                ('double_opted_in_at', models.DateTimeField(blank=True, null=True)),
                ('has_set_never_unsubscribe', models.BooleanField(default=False)),
                ('unsubscribed', models.BooleanField(default=False)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('opt_in_key', models.CharField(blank=True, db_index=True, max_length=254, null=True)),
                ('opt_in_key_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_action', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkmail.Newsletter')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('send_at_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('send_at_hour', models.IntegerField()),
                ('send_at_minute', models.IntegerField()),
                ('use_local_time', models.BooleanField(default=True)),
                ('num_scheduled', models.IntegerField(default=0)),
                ('num_sent', models.IntegerField(default=0)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inkmail.Message')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkmail.Newsletter')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingMessageAttemptTombstone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('send_time', models.DateTimeField()),
                ('encrypted_email', models.TextField(blank=True, null=True)),
                ('encrypted_message_subject', models.TextField(blank=True, null=True)),
                ('encrypted_message_body', models.TextField(blank=True, null=True)),
                ('send_success', models.NullBooleanField()),
                ('send_error', models.TextField(blank=True, null=True)),
                ('attempt_made', models.NullBooleanField()),
                ('reason', models.CharField(blank=True, max_length=254, null=True)),
                ('outgoing_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inkmail.OutgoingMessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='scheduled_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inkmail.ScheduledMessage'),
        ),
    ]
