# Generated by Django 2.2 on 2019-04-16 02:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('internal_name', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unsubscribe_if_no_hearts_after_days', models.BooleanField(default=False)),
                ('unsubscribe_if_no_hearts_after_days_num', models.IntegerField(blank=True, default=184, null=True)),
                ('unsubscribe_if_no_hearts_after_messages', models.BooleanField(default=True)),
                ('unsubscribe_if_no_hearts_after_messages_num', models.IntegerField(blank=True, default=26, null=True)),
                ('confirm_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_for_confirm', to='inkmail.Message')),
                ('welcome_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_for_welcome', to='inkmail.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='mailing_list',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='mailing_list',
        ),
        migrations.DeleteModel(
            name='MailingList',
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='newsletter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inkmail.Newsletter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='newsletter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inkmail.Newsletter'),
            preserve_default=False,
        ),
    ]
