# Generated by Django 2.2 on 2019-04-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='hashid',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='unsubscribe_footer',
            field=models.TextField(),
        ),
    ]
