# Generated by Django 2.2 on 2019-04-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='was_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='was_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
