# Generated by Django 2.2 on 2019-04-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0002_auto_20190426_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulednewslettermessage',
            name='send_at_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulednewslettermessage',
            name='send_at_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulednewslettermessage',
            name='use_local_time',
            field=models.BooleanField(default=False),
        ),
    ]
