# Generated by Django 2.2 on 2019-04-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0002_auto_20190419_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='import_source',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
