# Generated by Django 2.2 on 2019-04-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0003_auto_20190417_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
