# Generated by Django 2.2 on 2019-04-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0003_subscription_import_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='unsubscribe_hash',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
