# Generated by Django 2.2 on 2019-04-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0003_auto_20190426_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulednewslettermessage',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inkmail.Newsletter'),
        ),
    ]
