# Generated by Django 2.2 on 2019-04-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0004_subscription_unsubscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='from_email',
            field=models.TextField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='from_name',
            field=models.TextField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
