# Generated by Django 2.2 on 2019-04-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0004_auto_20190426_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='attempt_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
