# Generated by Django 2.2 on 2019-04-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0005_outgoingmessage_attempt_skipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='hard_bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
