# Generated by Django 2.2 on 2019-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0005_auto_20190422_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingmessage',
            name='transactional',
        ),
        migrations.AddField(
            model_name='message',
            name='transactional',
            field=models.BooleanField(default=False),
        ),
    ]
