# Generated by Django 2.2 on 2019-04-22 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0006_auto_20190422_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmessage',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inkmail.Subscription'),
        ),
    ]
