# Generated by Django 2.2 on 2019-04-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0006_outgoingmessage_hard_bounced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='attempt_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
