# Generated by Django 2.2.1 on 2019-05-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0007_outgoingmessage_attempt_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='favicon_image',
            field=models.ImageField(blank=True, null=True, upload_to='organization', verbose_name='Favicon'),
        ),
    ]
