# Generated by Django 2.2 on 2019-04-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0007_auto_20190422_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='transactional_no_unsubscribe_reason',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='transactional_send_reason',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='delete_hash',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='should_retry',
            field=models.BooleanField(default=False),
        ),
    ]
