# Generated by Django 2.2 on 2019-04-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0007_auto_20190417_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessageattempttombstone',
            name='attempt_made',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='outgoingmessageattempttombstone',
            name='reason',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
