# Generated by Django 2.2 on 2019-04-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0008_auto_20190417_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='transactional_footer',
            field=models.TextField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='unsubscribe_footer',
            field=models.TextField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribed_from_ip',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
