# Generated by Django 2.2.1 on 2019-05-15 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0008_organization_favicon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='favicon_image',
        ),
    ]
