# Generated by Django 2.2 on 2019-04-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0008_auto_20190422_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='valid_message',
            field=models.BooleanField(default=True),
        ),
    ]
