# Generated by Django 2.2 on 2019-04-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0009_auto_20190417_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='opt_in_key',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='opt_in_key_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
