# Generated by Django 2.2.1 on 2019-05-15 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20190515_2134'),
        ('inkmail', '0009_remove_organization_favicon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Resource'),
        ),
    ]
