# Generated by Django 2.2.13 on 2020-11-11 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20201111_0027'),
        ('inkmail', '0010_organization_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='productpurchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductPurchase'),
        ),
    ]
