# Generated by Django 2.2 on 2019-04-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0010_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='transactional_footer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
