# Generated by Django 2.2.1 on 2019-05-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0010_organization_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='robots_txt',
            field=models.TextField(blank=True, default='User-agent: *\nAllow: /', null=True),
        ),
    ]
