# Generated by Django 2.2 on 2019-04-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0011_organization_transactional_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='transactional_footer',
        ),
        migrations.AlterField(
            model_name='outgoingmessage',
            name='delete_hash',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='outgoingmessage',
            name='unsubscribe_hash',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
