# Generated by Django 2.2.1 on 2019-05-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0011_organization_robots_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='robots_txt',
            field=models.TextField(blank=True, default='User-agent: *\nAllow: /\n', null=True),
        ),
    ]
