# Generated by Django 2.2 on 2019-04-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0012_auto_20190422_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='love_hash',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
