# Generated by Django 2.2.13 on 2021-04-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0013_outgoingmessage_journey_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',)},
        ),
    ]
