# Generated by Django 2.2.13 on 2021-04-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0014_auto_20210414_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='resubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
