# Generated by Django 2.2 on 2019-04-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0014_auto_20190424_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='loved',
            field=models.BooleanField(default=False),
        ),
    ]
