# Generated by Django 2.2 on 2019-04-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkmail', '0015_outgoingmessage_loved'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='loved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
